# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: managementGroups
    steps:
      - 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Management Group'
    azureResourceManagerConnection: 'ALZ-XSmall SUB'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/msabeq94/ALZ-XSmall/blob/XSmallV4/MainXSmall.bicep'
    csmParametersFileLink: 'https://github.com/msabeq94/ALZ-XSmall/blob/XSmallV4/Main.parameters.XSmall.json'
    deploymentMode: 'Incremental'

