# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: default

parameters:
  - name: customer_client_id
    displayName: "Customer Client ID"
    type: object
    default: "f084242d-5811-4cac-accc-4377318b9e39"

  - name: customer_client_secret
    displayName: "Customer Client Secret"
    type: object
    default: "g9w8Q~zt.EResb09c_icBvcLrWILVHuZ.-k0NbeS"
  
  - name: customer_tenant_id
    displayName: "Customer Tenant ID"
    type: object
    default: "87431d80-c13c-4f97-8d52-4bd5ec6e617e"

  - name: customer_subscription_id
    displayName: "Customer Subscription ID"
    type: object
    default: "102170e2-9371-4b66-95de-d4530f8bf56e"

  - name: customer_name
    displayName: "Customer Name"
    type: object
    default: "mos"

  - name: customer_location
    displayName: "Customer location"
    type: object
    default: "eastus"



stages:
- stage: Stage1
  jobs:
  - job: login
    steps:
    - script: az login --service-principal --username ${{ parameters.customer_client_id}} --password ${{ parameters.customer_client_secret }} --tenant ${{ parameters.customer_tenant_id }}
      displayName: 'login'

- stage: Stage2
  dependsOn: Stage1
  jobs:
  - job: update_bicep_file
    steps:
    - script: | 
        sed -i "s/customerLocation/${{parameters.customer_location}}/g" Main.parameters.XSmall.json
        sed -i "s/customerName/${{parameters.customer_name}}/g" managementGroups.parameters.XSmall.json
        sed -i "s/mgmtSubID/${{parameters.customer_subscription_id}}/g" Main.parameters.XSmall.json
        sed -i "s/mgmtSubID/${{parameters.customer_subscription_id}}/g" Modules/FWXSmall.bicep
        sed -i "s/mgmtSubID/${{parameters.customer_subscription_id}}/g" Modules/PolicyassignmentsXSmal.bicep
        cat Main.parameters.XSmall.json
      displayName: 'update_bicep_file'

- stage: Stage3
  dependsOn: Stage2
  jobs:
    - job: Run_bicep_file_MG
      steps:
      - script: az deployment tenant create --name 'run bicep'  --location ${{parameters.customer_location}} --template-file "managementGroupsXSmall.bicep"  --parameters "managementGroups.parameters.XSmall.json"
        
        displayName: 'Run_bicep_MG_file'











      