trigger: none

pool: default

parameters:
  - name: customer_client_id
    displayName: "Customer Client ID"
    type: object
    default: "f084242d-5811-4cac-accc-4377318b9e39"

  - name: customer_client_secret
    displayName: "Customer Client Secret"
    type: object
    default: "g9w8Q~zt.EResb09c_icBvcLrWILVHuZ.-k0NbeS"
  
  - name: customer_tenant_id
    displayName: "Customer Tenant ID"
    type: object
    default: "87431d80-c13c-4f97-8d52-4bd5ec6e617e"

  - name: customer_subscription_id
    displayName: "Customer Subscription ID"
    type: object
    default: "102170e2-9371-4b66-95de-d4530f8bf56e"

  - name: customer_name
    displayName: "Customer Name"
    type: object
    default: "mos"

  - name: customer_location
    displayName: "Customer location"
    type: object
    default: "eastus"

  - name: dateYMD
    displayName: "dateYMD"
    type: object
    default: "$(date +%Y%m%dT%H%M%S%NZ)"

  - name: NAME
    displayName: "NAME"
    type: object
    default: "alz-MgDeployment-mos"

stages:
- stage: AuthenticateAzure
  jobs:
  - job: AuthenticateServicePrincipal
    steps:
    - script: az login --service-principal --username ${{ parameters.customer_client_id}} --password ${{ parameters.customer_client_secret }} --tenant ${{ parameters.customer_tenant_id }}
      displayName: 'Authenticate Service Principal'
      
- stage: DeployManagementGroups
  dependsOn: AuthenticateAzure
  jobs:
  - job: DeployManagementGroupBicep
    steps:
    - script: | 
        sed -i "s/customerName/${{parameters.customer_name}}/g" managementGroups.parameters.XSmall.json
        az deployment tenant create --name ${{parameters.NAME}}  --location ${{parameters.customer_location}} --template-file "managementGroupsXSmall.bicep"  --parameters "managementGroups.parameters.XSmall.json"
      displayName: 'Deploy Management Group Bicep'

- stage:  DeployMainInfrastructure
  dependsOn: AuthenticateAzure
  jobs:
  - job: DeployMainBicepModules
    steps:
    - script: |
        sed -i "s/customerLocation/${{parameters.customer_location}}/g" Main.parameters.XSmall.json
        sed -i "s/mgmtSubID/${{parameters.customer_subscription_id}}/g" Main.parameters.XSmall.json
        sed -i "s/mgmtSubID/${{parameters.customer_subscription_id}}/g" Modules/FWXSmall.bicep
        sed -i "s/mgmtSubID/${{parameters.customer_subscription_id}}/g" Modules/PolicyassignmentsXSmall.bicep
        az deployment sub create --name ${{parameters.NAME}}  --location ${{parameters.customer_location}} --template-file "MainXSmall.bicep"  --parameters "Main.parameters.XSmall.json"
      displayName: 'Deploy Main Bicep File'

- stage: AssignResourcesToManagementGroups
  dependsOn: DeployManagementGroups
  jobs:
    - job:  AssignSubscriptionsToManagementGroups
      steps:
      - script: |
            az account management-group subscription add --name 'alz-landingzones-online' -s ${{parameters.customer_subscription_id}}
      displayName: 'Assign Subscription to Management Groups'


- stage: CleanUpResources
  dependsOn: DeployMainInfrastructure
  jobs:
        - job: ManualApprovalResourcesStep
          displayName: "Review and Approve Resources Cleanup"
          pool: server  # Ensures the job runs without an agent
          steps:
            - task: ManualValidation@0
              inputs:
                notifyUsers: 'msabeq@outlook.com'  # Replace with the actual approver's email
                instructions: 'Please approve or reject the execution of resource cleanup.'
        - job: RemoveResources
          dependsOn: ManualApprovalResourcesStep
          steps:
            - script: |
                az group delete --name "vf-core-InternalServices-rg" --yes 
                az group delete --name "vf-core-Production-rg" --yes 
                az group delete --name "vf-core-Development-rg" --yes 
                az group delete --name "vf-core-CentralHub-rg" --yes 
              displayName: 'Delete Resources'

- stage: CleanUpManagementGroups
  dependsOn: AssignResourcesToManagementGroups
  jobs:
        - job: ManualApprovalManagementGroupsStep
          displayName: "Review and Approve ManagementGroups Cleanup"
          pool: server  # Ensures the job runs without an agent
          steps:
            - task: ManualValidation@0
              inputs:
                notifyUsers: 'msabeq@outlook.com'  # Replace with the actual approver's email
                instructions: 'Please approve or reject the execution of ManagementGroups cleanup.'
        - job: RemoveManagementGroups
          dependsOn: ManualApprovalManagementGroupsStep
          steps:
            - script: |
                # Add your script here
                az account management-group subscription remove --name 'alz-landingzones-online' -s ${{parameters.customer_subscription_id}}
                 az account management-group delete --name alz-landingzones-online
                 az account management-group delete --name alz-landingzones
                 az account management-group delete --name alz           
              displayName: 'Delete ManagementGroups'
    
